---
title: "About the FEWsLab"
format: html
page-layout: full
toc: true
toc-location: left
---

# Sustainability, Systems, and Environmental Ethics

The FEWsLab investigates interconnections across **food**, **energy**, and **water** systems. Our research integrates **network modeling**, **socio-technical data**, and **ethical analysis** to advance both policy and research questions in the areas of risk, resilience, and sustainability. We strive to bridge the gap between advancements in theory and useful insights for decision makers that address pressing global challenges.

---

# Who We Are

The FEWsLab is led by **Dr. Caitlin Grady**, Associate Professor of Engineering Management and Systems Engineering at George Washington University and Director of Research at the [Global Food Institute](https://globalfoodinstitute.gwu.edu/). Dr. Grady brings a combination of academic, policy, and government experience. She has previously served as a faculty member at Penn State, a Policy Analyst at the U.S. Department of State and the Department of Energy, and as a Legislative Assistant in the U.S. Congress. Our lab thrives thanks to a talented and unique team of researchers, students, and collaborators who share a commitment to thinking outside the box.

---

# Research

Our research is supported by the **National Science Foundation**, the **U.S. Department of Agriculture**, the **McGovern Foundation** and other institutional partners. We pursue interdisciplinary projects that address complex challenges through systems thinking, data-driven modeling, and policy-relevant analysis.

---

# News and Highlights

- Dr. Grady was recently named the next Director of Research for the [Global Food Institute](https://globalfoodinstitute.gwu.edu/)
- Abbey Kollar and Ji Qi presented recent research at the 10th International Engineering Systems Symposium hosted by [CESUN](https://cesun.org/)
- Dr. Grady was quoted in a recent episode of NPR's All Things Considered [July 4, 2025](https://www.npr.org/2025/07/04/nx-s1-5454884/why-hydropower-faces-more-barriers-than-wind-or-solar)
- Dhanyasri Bolla was invited to present our work on Adaptation in Megacities to the IDB Annual Meeting of the Chief Audit Executives of the Multilateral Financial Institutions

